eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    non-secure-port: 80
    non-secure-port-enabled: true
  client:
    service-url:
      defaultZone: ${peer1.url}/eureka,${peer2.url}/eureka
      #${vcap.services.discovery-server-eureka-peer11-ups.credentials.url:localhost}/eureka
    